version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
    open-pull-requests-limit: 50
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "updates"
    open-pull-requests-limit: 50
    allow:
      - dependency-type: "development"
      - dependency-type: "indirect"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "beta"
    open-pull-requests-limit: 50
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"
    target-branch: "updates"
    open-pull-requests-limit: 50
    allow:
      - dependency-type: "development"
