version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "updates"
      
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"
    target-branch: "updates"
      
  - package-ecosystem: "npm"
    directory: "/proxy"
    schedule:
      interval: "monthly"
    target-branch: "updates"
